### ISSUE TITLE
Catalog Controller Facet Query Label Limits

### ISSUE THREAD

**Issue by leeheeman** [projectblacklight/projectblacklight.github.com#2]
In my catalog_controller.rb I have been adding a lot of custom query labels such as below.

config.add_facet_field 'example_data', :label => 'Example Label', :limit => 38, :sort => 'index', :query => {
:example_query => { :label => 'Example Label2', :fq => "example_data:EXAMPLEQUERY"},
...
...
}
I was trying to add over 100 of these things. Everything was going fine until I got the broken pipe error.  It seems there is a limit to how many of these things I can add. My app is working fine now, but I cannot write in any more without either getting the Broken Pipe error or error 400.

Has anyone else tried anything like that or have any idea how to get around it?

**Comment by erikhatcher** [comment]
This may be a Solr URL length issue?   I'm not sure the Blacklight
incantation, but the easiest most common fix is to set requests from
Blacklight to Solr to POST, rather than GET.

The bummer with POST is you will no longer see the full request params
logged in Solr logs.   One other option might be to configure your
container (Jetty?  Tomcat?) to a longer GET URL length maximum.

And yet another option is to put these facet queries into your Solr
configuration, in the request handler(s) that you need them.  (these end up
as facet.query's, right?)

```
Erik
```

**Comment by jcoyne** [comment]
The configuration parameter you're looking for is:

```
config.http_method=:post
```

As @erikhatcher said, there are other alternatives for preventing this situation, each with their own set of benefits and disadvantages.

P.S. Issues about blacklight itself should be posted to https://github.com/projectblacklight/blacklight/issues
